---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: O Cloud Volumes ONTAP 9.14.1 inclui uma nova melhoria. 
---
= Novidades do Cloud Volumes ONTAP 9.14.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.14.1 inclui novos aprimoramentos.

Recursos e aprimoramentos adicionais também são introduzidos nas versões mais recentes do BlueXP . Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de versão do BlueXP"^] para obter detalhes.



== 9.14.1 P7 (29 de agosto de 2024)

O patch 9.14.1 P7 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P7["Veja a lista de bugs corrigidos no patch P7"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.14.1 P6 (18 de julho de 2024)

O patch 9.14.1 P6 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P6["Veja a lista de bugs corrigidos no patch P6"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.14.1 P5 (3 de julho de 2024)

O patch 9.14.1 P5 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P5["Veja a lista de bugs corrigidos no patch P5"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.14.1 P4 (3 de julho de 2024)

O patch 9.14.1 P4 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P4["Veja a lista de bugs corrigidos no patch P4"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.14.1 P2 (18 de abril de 2024)

O patch 9.14.1 P2 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P2["Veja a lista de bugs corrigidos no patch P2"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.14.1 P1 (1 de abril de 2024)

O patch 9.14.1 P1 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P1["Veja a lista de bugs corrigidos no patch P1"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.14.1 GA (5 de março de 2024)

A versão de disponibilidade geral do Cloud Volumes ONTAP 9.14.1 já está disponível na AWS, Azure e Google Cloud.



== 9.14.1 RC1 (6 de dezembro de 2023)

O Release Candidate 1 do Cloud Volumes ONTAP 9.14.1 já está disponível na AWS, Azure e Google Cloud.



== Notas de atualização

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do BlueXP . Você não deve atualizar o Cloud Volumes ONTAP usando o Gerenciador de sistema ou a CLI. Isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Saiba como atualizar quando o BlueXP  o notificar"^].



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.14.1 a partir de versões 9.13.1 e 9.14.0. A BlueXP  solicitará que você atualize os sistemas Cloud Volumes ONTAP qualificados para esta versão.



=== Versão necessária do conetor

O conetor BlueXP  deve estar executando a versão 3.9.27 ou posterior para implantar novos sistemas Cloud Volumes ONTAP 9.14.1 e atualizar os sistemas existentes para o 9.14.1.


TIP: As atualizações automáticas do conetor são ativadas por padrão, portanto, você deve estar executando a versão mais recente.



=== Tempo de inatividade

* A atualização de um sistema de nó único leva o sistema off-line por até 25 minutos, durante os quais a e/S é interrompida.
* A atualização de um par de HA não causa interrupções e e/S é ininterrupta. Durante esse processo de atualização sem interrupções, cada nó é atualizado em conjunto para continuar fornecendo e/S aos clientes.




=== as instâncias c4, m4 e r4 não são mais compatíveis

Na AWS, os tipos de instância C4, M4 e R4 EC2 não são mais compatíveis com o Cloud Volumes ONTAP. Se você tiver um sistema existente que esteja sendo executado em um tipo de instância C4, M4 ou R4, será necessário alterar para um tipo de instância na família de instâncias C5, M5 ou R5. Não é possível atualizar para esta versão até alterar o tipo de instância.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Saiba como alterar o tipo de instância EC2 para Cloud Volumes ONTAP"^].

link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Suporte à NetApp"^]Consulte para saber mais sobre o fim da disponibilidade e suporte para esses tipos de instância.
